project:
  name: "Person-Re-Identification"
  experiment_name: "BPBreID"
  logger:
    use_clearml: False
    use_neptune: False
    use_tensorboard: False
    matplotlib_show: False
    use_wandb: False

data:
  root: '~/datasets/reid'
  type: 'image'
  sources: ['synergy']
  targets: ['synergy']
  height: 256
  width: 128
  combineall: False
  transforms: []
  ro:
    path: "/Users/vladimirsomers/datasets/other/VOCdevkit/VOC2012"
  masks:
    preprocess: 'five_v'  # 'none', 'full', 'id', 'ids', 'bs_fu', 'bs_fu_bb', 'mu_sc', 'four', 'four_no', 'four_v', 'four_v_pif', 'five_v', 'six', 'six_no', 'eight'
    background_computation_strategy: 'threshold'  # threshold, diff_from_max
    softmax_weight: 15
    mask_filtering_threshold: 0.6
  save_dir: '/Users/vladimirsomers/Code/logs/deep-person-reid/resnet50_synergy_pose'
  masks_dir: 'pifpaf'
  workers: 0

sampler:
  train_sampler: RandomIdentitySampler # sampler for source train loader
  train_sampler_t: RandomIdentitySampler # sampler for target train loader
  num_instances: 3 # number of instances per identity for RandomIdentitySampler

model:
  name: 'bpbreid'
  pretrained: True
#  load_weights: 'pretrained_models/posenet_bp_loss_intra_id_max_mask_filtering.pth'
  save_model_flag: False
  bpbreid:
    pooling: 'gwap'
    normalization: 'identity'
    mask_filtering_training: False
    mask_filtering_testing: True
    last_stride: 1
    learnable_attention_enabled: True
    dim_reduce: 'none' # 'none', 'before_pooling', 'after_pooling', 'after_pooling_with_dropout'
    dim_reduce_output: 512
    backbone: 'resnet50' # 'hrnet32' 'resnet50'
    test_embeddings: ['foreg', 'parts'] #  ['globl', 'foreg', 'parts']
    test_use_target_segmentation: 'none' # 'none' 'hard' 'soft'

# test
test:
  evaluate: True # test only
  rerank: False
  batch_size: 20
  batch_size_pairwise_dist_matrix: 5000
  normalize_feature: True
  dist_metric: 'cosine' # ['euclidean', 'cosine']
  visrank: True
  visrank_per_body_part: False
  vis_embedding_projection: False
  vis_feature_maps: False
  visrank_topk: 10
  visrank_count: 2
  part_based:
    dist_combine_strat: mean