project:
  name: "Person-Re-Identification"
  experiment_name: "BPBreID"
  logger:
    use_clearml: False
    use_neptune: False
    use_tensorboard: False
    matplotlib_show: False
    use_wandb: False

data:
  root: '~/datasets/reid'
  type: 'image'
  sources: ['synergy']
  targets: ['synergy']
  height: 256
  width: 128
  combineall: False
  transforms: ['rc', 'rf', 're']
  masks:
    preprocess: 'id'  # 'none', 'full', 'id', 'ids', 'bs_fu', 'bs_fu_bb', 'mu_sc', 'four', 'four_no', 'four_v', 'four_v_pif', 'five', 'five_v', 'six', 'six_no', 'seven_v', 'eight', 'eight_v', 'ten_ms', 'eleven', 'fourteen', 'fourteen'
    background_computation_strategy: 'threshold'  # threshold, diff_from_max
    softmax_weight: 15
    mask_filtering_threshold: 0.5
  save_dir: '/Users/vladimirsomers/Code/logs/deep-person-reid/bot_synergy'
  masks_dir: 'pifpaf' # 'pifpaf' 'pifpaf_maskrcnn_filtering' 'isp_6_parts'
  workers: 0

sampler:
  train_sampler: RandomIdentitySampler # sampler for source train loader
  train_sampler_t: RandomIdentitySampler # sampler for target train loader
  num_instances: 3 # number of instances per identity for RandomIdentitySampler

model:
  name: 'bpbreid'
  pretrained: True
#  load_weights: 'pretrained_models/posenet_bp_loss_intra_id_max_mask_filtering.pth'
  save_model_flag: False
  bpbreid:
    pooling: 'gap'  # ['gap', 'gmp', 'gwap', 'gwap2']
    normalization: 'identity' # 'batch_norm_2d' 'identity'
    mask_filtering_training: False
    mask_filtering_testing: False
    training_binary_visibility_score: True
    testing_binary_visibility_score: True
    last_stride: 1
    learnable_attention_enabled: False
    dim_reduce: 'none' # 'none', 'before_pooling', 'after_pooling', 'after_pooling_with_dropout', 'after_pooling_pcb'
    dim_reduce_output: 512
    backbone: 'resnet50' # 'hrnet32' 'resnet50' 'fastreid_resnet' 'fastreid_resnet_ibn' 'fastreid_resnet_nl' 'fastreid_resnet_ibn_nl'
    test_embeddings: ['bn_globl'] #  ['globl', 'foreg', 'conct', 'parts']
    test_use_target_segmentation: 'none' # 'none' 'hard' 'soft'
    shared_parts_id_classifier: False
    normalized_bned_embeddings: False

loss:
  name: 'part_based'
  triplet:
    margin: 0.3
  part_based:
    name: 'part_based_triplet_loss_mean' # ['inter_parts_triplet_loss', 'intra_parts_triplet_loss', 'part_based_triplet_loss_max', 'part_based_triplet_loss_mean', 'part_based_triplet_loss_min', 'part_based_triplet_loss_max_min', 'part_based_triplet_loss_random_max_min']
    weights:
      globl:
        ce: 1.
        tr: 1.
      foreg:
        ce: 0.
        tr: 0.
      conct:
        ce: 0.
        tr: 0.
      parts:
        ce: 0.
        tr: 0.
      pixls:
        ce: 0.

train:
  batch_size: 30
  eval_freq: 5
  max_epoch: 10
  optim: 'adam' # 'adam', 'amsgrad', 'sgd', 'rmsprop', 'radam'
  lr: 0.00035
  lr_scheduler: 'single_step' # 'single_step' 'multi_step' 'cosine'
  stepsize: [40, 70] # stepsize to decay learning rate
  fixbase_epoch: 0
  open_layers: ['global_avgpool', 'foreground_global_attention_pooling_head', 'background_global_attention_pooling_head',
                'global_attention_pooling_head', 'pixel_classifier', 'global_identity_classifier',
                'background_identity_classifier', 'foreground_identity_classifier', 'parts_identity_classifier']

# test
test:
  batch_size: 30
  batch_size_pairwise_dist_matrix: 5000
  normalize_feature: True
  dist_metric: 'euclidean' # distance metric, ['euclidean', 'cosine']
  evaluate: False # test only
  visrank: False
  visrank_per_body_part: False
  vis_embedding_projection: False
  vis_feature_maps: False
  visrank_topk: 10
  visrank_count: 2
  part_based:
    dist_combine_strat: mean
