project:
    name: "Person-Re-Identification"
    experiment_name: ""
    notes: "PCB"
    tags: []
    logger:
      use_clearml: False
      use_neptune: False
      use_tensorboard: True
      use_wandb: True

data:
  root: '~/datasets/reid'
  type: 'image'
  sources: ['dukemtmcreid']
  targets: ['dukemtmcreid']
  height: 384
  width: 128
  combineall: False
  transforms: ['rc', 'rf', 're']
  masks:
    preprocess: 'strp_6'
  save_dir: '/home/vso/log/bpbreid_occluded_duke'
  workers: 10

sampler:
  train_sampler: RandomIdentitySampler # sampler for source train loader
  train_sampler_t: RandomIdentitySampler # sampler for target train loader
  num_instances: 4 # number of instances per identity for RandomIdentitySampler

model:
  name: 'bpbreid'
  pretrained: True
  save_model_flag: False
  bpbreid:
    pooling: 'gwap'  # ['gap', 'gmp', 'gwap', 'gwap2']
    normalization: 'identity' # 'batch_norm_2d' 'identity'
    mask_filtering_training: False
    mask_filtering_testing: False
    training_binary_visibility_score: True
    testing_binary_visibility_score: True
    last_stride: 1
    learnable_attention_enabled: False
    dim_reduce: 'after_pooling' # 'none', 'before_pooling', 'after_pooling', 'after_pooling_with_dropout'
    dim_reduce_output: 512
    backbone: 'hrnet32' # 'hrnet32' 'resnet50'
    test_embeddings: ['conct'] #  ['globl', 'foreg', 'conct', 'parts']
    test_use_target_segmentation: 'none' # 'none' 'hard' 'soft'
    shared_parts_id_classifier: False

loss:
  name: 'part_based'
  part_based:
    name: 'part_based_triplet_loss_mean' # ['inter_parts_triplet_loss', 'intra_parts_triplet_loss', 'part_based_triplet_loss_max', 'part_based_triplet_loss_mean', 'part_based_triplet_loss_min', 'part_based_triplet_loss_max_min', 'part_based_triplet_loss_random_max_min']
    weights:
      globl:
        ce: 0.
        tr: 0.
      foreg:
        ce: 0.
        tr: 0.
      conct:
        ce: 0.
        tr: 0.
      parts:
        ce: 1.
        tr: 0.

train:
  batch_size: 64
  eval_freq: 0
  max_epoch: 120 # 45 120
  stepsize: [40, 70] # [40, 70] [25, 35]
  optim: 'adam' # 'adam', 'amsgrad', 'sgd', 'rmsprop', 'radam'
  lr: 0.00035
  lr_scheduler: 'warmup_multi_step' # 'single_step' 'multi_step' 'cosine' 'warmup_multi_step'
  fixbase_epoch: 0
  open_layers: ['global_avgpool', 'foreground_global_attention_pooling_head', 'background_global_attention_pooling_head',
                'global_attention_pooling_head', 'pixel_classifier', 'global_identity_classifier',
                'background_identity_classifier', 'foreground_identity_classifier', 'parts_identity_classifier']

test:
  start_eval: 40
  batch_size: 128
  batch_size_pairwise_dist_matrix: 5000
  normalize_feature: True
  dist_metric: 'cosine' # ['euclidean', 'cosine']
  visrank: False
  visrank_per_body_part: False
  vis_embedding_projection: False
  vis_feature_maps: False
  visrank_topk: 10
  visrank_count: 11
  visrank_q_idx_list: [ 363, 942, 1974, 2013, 2081, 2145, 2207, 13, 506, 1695, 1772 ]
  #  363 - 0114_c1_f0072838.jpg
  #  942 - 4804_c6_f0202700.jpg
  #  1974 - 0076_c1_f0065392.jpg
  #  2013 - 4681_c6_f0155553.jpg
  #  2081 - 4760_c7_f0184430.jpg
  #  2145 - 0749_c1_f0188383.jpg
  #  2207 - 4726_c6_f0169726.jpg
  part_based:
    dist_combine_strat: mean
