project:
    name: "Person-Re-Identification"
    experiment_name: ""
    notes: ""
    tags: []
    logger:
      use_clearml: False
      use_neptune: False
      use_tensorboard: True
      use_wandb: True

data:
  root: '~/datasets/reid'
  type: 'image'
  sources: ['market1501']
  targets: ['market1501', 'occluded_reid']
  height: 384 # 384
  width: 128 # 192
  combineall: False
  transforms: ['rc', 're', 'rf', 'cj']
  masks:
    preprocess: 'eight'  # 'none', 'full', 'id', 'ids', 'bs_fu', 'bs_fu_bb', 'mu_sc', 'four', 'four_no', 'four_v', 'four_v_pif', 'five', 'five_v', 'six', 'six_no', 'seven_v', 'eight', 'eight_v', 'ten_ms', 'eleven', 'fourteen', 'fourteen'
    background_computation_strategy: 'threshold'  # threshold, diff_from_max
    softmax_weight: 15
    mask_filtering_threshold: 0.5
  save_dir: '/home/vso/log/bpbreid_occluded_duke'
  masks_dir: 'pifpaf_maskrcnn_filtering' # 'pifpaf' 'pifpaf_maskrcnn_filtering' 'isp_6_parts'
  workers: 6

model:
  name: 'bpbreid'
  pretrained: True
#  load_weights: "/home/vso/log/bpbreid_occluded_duke/9371/2022_08_19_22_27_15_27S5f3eaa60-da2a-441b-846d-856735ed8a39model/job-9371_120_model.pth.tar"
  load_weights: "/home/vso/log/bpbreid_occluded_duke/9425/2022_08_21_13_03_00_03Se3816403-97db-4b8c-92e3-f7881617b9bcmodel/job-9425_120_model.pth.tar"
  save_model_flag: True
  bpbreid:
    pooling: 'gwap'  # ['gap', 'gmp', 'gwap', 'gwap2']
    normalization: 'identity' # 'batch_norm_2d' 'identity'
    mask_filtering_training: False
    mask_filtering_testing: True
    training_binary_visibility_score: True
    testing_binary_visibility_score: True
    last_stride: 1
    learnable_attention_enabled: True
    dim_reduce: 'after_pooling' # 'none', 'before_pooling', 'after_pooling', 'after_pooling_with_dropout', 'after_pooling_pcb'
    dim_reduce_output: 512
    backbone: 'hrnet32' # 'hrnet32' 'resnet50' 'fastreid_resnet' 'fastreid_resnet_ibn' 'fastreid_resnet_nl' 'fastreid_resnet_ibn_nl'
    test_embeddings: ['bn_foreg', 'parts'] #  ['globl', 'foreg', 'conct', 'parts']
    test_use_target_segmentation: 'none' # 'none' 'hard' 'soft'
    shared_parts_id_classifier: False
    normalized_bned_embeddings: False

test:
  evaluate: True # test only
  rerank: False
  start_eval: 90
  detailed_ranking: False
  batch_size: 128
  batch_size_pairwise_dist_matrix: 5000
  normalize_feature: True
  dist_metric: 'euclidean' # ['euclidean', 'cosine']
  visrank: True
  visrank_per_body_part: False
  vis_embedding_projection: False
  vis_feature_maps: False
  visrank_topk: 10
  visrank_count: 11
  part_based:
    dist_combine_strat: mean
