project:
    name: "Person-Re-Identification"
    experiment_name: ""
    notes: ""
    tags: []
    logger:
      use_clearml: False
      use_neptune: False
      use_tensorboard: True
      use_wandb: True

data:
  root: '~/datasets/reid'
  type: 'image'
  sources: ['occluded_duke']
  targets: ['occluded_duke']
  height: 256
  width: 128
  combineall: False
  transforms: ['rc', 'rf', 're']
  masks:
    preprocess: 'strp_6'
  save_dir: '/home/vso/log/bpbreid_occluded_duke'
  workers: 10

sampler:
  train_sampler: RandomIdentitySampler # sampler for source train loader
  train_sampler_t: RandomIdentitySampler # sampler for target train loader
  num_instances: 4 # number of instances per identity for RandomIdentitySampler

model:
  name: 'bpbreid'
  pretrained: True
  #
#  load_weights: '/home/vso/log/posenet_occluded_duke/2022_02_27_22_01_43_01S0e0b2e27-a9aa-4da1-99e5-5ed3be939d1d/2022_02_27_22_01_43_01S0e0b2e27-a9aa-4da1-99e5-5ed3be939d1dmodel/model.pth.tar-120'
  # 7526
#  load_weights: "/home/vso/log/posenet_occluded_duke/2022_03_02_19_15_42_15S2fa16d9a-7b09-4def-9688-77224213dd18/2022_03_02_19_15_42_15S2fa16d9a-7b09-4def-9688-77224213dd18model/model.pth.tar-120"
  # 7527
#  load_weights: "/home/vso/log/posenet_occluded_duke/2022_03_02_19_54_21_54Scf95f5af-a668-4c2a-bc34-e2ee648ada7f/2022_03_02_19_54_21_54Scf95f5af-a668-4c2a-bc34-e2ee648ada7fmodel/model.pth.tar-120"
  # 7536
#  load_weights: "/home/vso/log/posenet_occluded_duke/2022_03_02_22_24_31_24Sef9c1446-e965-4f3a-8944-96c4d203121d/2022_03_02_22_24_31_24Sef9c1446-e965-4f3a-8944-96c4d203121dmodel/model.pth.tar-120"
  # 7537
#  load_weights: "/home/vso/log/posenet_occluded_duke/2022_03_02_22_25_04_25Sa344ff6e-a418-4244-a49e-3ae7ddc7b6c7/2022_03_02_22_25_04_25Sa344ff6e-a418-4244-a49e-3ae7ddc7b6c7model/model.pth.tar-120"
  # 7528
  load_weights: "/home/vso/log/posenet_occluded_duke/2022_03_02_20_04_04_04S05dc0057-3b9e-47d5-9eab-189b4e3e9be7/2022_03_02_20_04_04_04S05dc0057-3b9e-47d5-9eab-189b4e3e9be7model/model.pth.tar-120"
  # 7539
#  load_weights: "/home/vso/log/posenet_occluded_duke/2022_03_02_22_32_09_32Sa70e7c5b-b874-4394-8469-73fcbc5598bb/2022_03_02_22_32_09_32Sa70e7c5b-b874-4394-8469-73fcbc5598bbmodel/model.pth.tar-120"
  # 7540
#  load_weights: "/home/vso/log/posenet_occluded_duke/2022_03_02_23_10_08_10Scd43aa77-178a-466f-8baf-349db0726b4f/2022_03_02_23_10_08_10Scd43aa77-178a-466f-8baf-349db0726b4fmodel/model.pth.tar-120"
  # 7541
#  load_weights: "/home/vso/log/posenet_occluded_duke/2022_03_02_23_10_08_10Sb944b2b1-60f7-468c-864f-89f30f3ce6e3/2022_03_02_23_10_08_10Sb944b2b1-60f7-468c-864f-89f30f3ce6e3model/model.pth.tar-120"
  # 7545
#  load_weights: "/home/vso/log/posenet_occluded_duke/2022_03_03_01_08_31_08Se06da2d1-9ed3-4dd7-a154-d5a41918824e/2022_03_03_01_08_31_08Se06da2d1-9ed3-4dd7-a154-d5a41918824emodel/model.pth.tar-120"
  # 7544
#  load_weights: "/home/vso/log/posenet_occluded_duke/2022_03_03_00_47_10_47Sdccd8725-e134-442b-ae44-084bcfb107a9/2022_03_03_00_47_10_47Sdccd8725-e134-442b-ae44-084bcfb107a9model/model.pth.tar-120"
  # 7543
#  load_weights: "/home/vso/log/posenet_occluded_duke/2022_03_03_00_39_25_39S487d5a71-38fd-4a87-9dac-d57354c38b69/2022_03_03_00_39_25_39S487d5a71-38fd-4a87-9dac-d57354c38b69model/model.pth.tar-120"
  # 7542
#  load_weights: "/home/vso/log/posenet_occluded_duke/2022_03_03_00_18_15_18S262e9658-15e9-45d6-83ae-8c4b5f57d900/2022_03_03_00_18_15_18S262e9658-15e9-45d6-83ae-8c4b5f57d900model/model.pth.tar-120"
  bpbreid:
    pooling: 'gwap'  # ['gap', 'gmp', 'gwap', 'gwap2']
    normalization: 'identity' # 'batch_norm_2d' 'identity'
    mask_filtering_training: False
    mask_filtering_testing: False
    training_binary_visibility_score: True
    testing_binary_visibility_score: True
    last_stride: 1
    learnable_attention_enabled: False
    dim_reduce: 'none' # 'none', 'before_pooling', 'after_pooling', 'after_pooling_with_dropout'
    dim_reduce_output: 512
    backbone: 'resnet50' # 'hrnet32' 'resnet50'
    test_embeddings: ['conct'] #  ['globl', 'foreg', 'conct', 'parts']
    test_use_target_segmentation: 'none' # 'none' 'hard' 'soft'
    shared_parts_id_classifier: False

loss:
  name: 'part_based'
  part_based:
    name: 'part_based_triplet_loss_mean' # ['inter_parts_triplet_loss', 'intra_parts_triplet_loss', 'part_based_triplet_loss_max', 'part_based_triplet_loss_mean', 'part_based_triplet_loss_min', 'part_based_triplet_loss_max_min', 'part_based_triplet_loss_random_max_min']
    weights:
      globl:
        ce: 1.
        tr: 0.
      foreg:
        ce: 1.
        tr: 0.
      conct:
        ce: 1.
        tr: 0.
      parts:
        ce: 0.
        tr: 1.

train:
  batch_size: 64
  eval_freq: 0
  max_epoch: 120 # 45 120
  stepsize: [40, 70] # [40, 70] [25, 35]
  optim: 'adam' # 'adam', 'amsgrad', 'sgd', 'rmsprop', 'radam'
  lr: 0.00035
  lr_scheduler: 'warmup_multi_step' # 'single_step' 'multi_step' 'cosine' 'warmup_multi_step'
  fixbase_epoch: 0
  open_layers: ['global_avgpool', 'foreground_global_attention_pooling_head', 'background_global_attention_pooling_head',
                'global_attention_pooling_head', 'pixel_classifier', 'global_identity_classifier',
                'background_identity_classifier', 'foreground_identity_classifier', 'parts_identity_classifier']

test:
  evaluate: True # test only
  start_eval: 40
  batch_size: 128
  batch_size_pairwise_dist_matrix: 5000
  normalize_feature: True
  dist_metric: 'cosine' # ['euclidean', 'cosine']
  visrank: False
  visrank_per_body_part: False
  vis_embedding_projection: False
  vis_feature_maps: False
  visrank_topk: 10
  visrank_count: 11
  visrank_q_idx_list: [ 363, 942, 1974, 2013, 2081, 2145, 2207, 13, 506, 1695, 1772 ]
  #  363 - 0114_c1_f0072838.jpg
  #  942 - 4804_c6_f0202700.jpg
  #  1974 - 0076_c1_f0065392.jpg
  #  2013 - 4681_c6_f0155553.jpg
  #  2081 - 4760_c7_f0184430.jpg
  #  2145 - 0749_c1_f0188383.jpg
  #  2207 - 4726_c6_f0169726.jpg
  part_based:
    dist_combine_strat: mean
