project:
    name: "Person-Re-Identification"
    experiment_name: ""
    notes: ""
    tags: ["test"]
    logger:
      use_clearml: False
      use_neptune: False
      use_tensorboard: True
      use_wandb: True

data:
  root: '~/datasets/reid'
  type: 'image'
  sources: ['market1501']
  targets: ['occluded_reid', 'partial_reid', 'partial_ilids', 'p_ETHZ', 'p_dukemtmc_reid']
  height: 384
  width: 128
  combineall: False
  transforms: ['rc', 're']
  masks:
    preprocess: 'five_v'  # 'none', 'full', 'id', 'ids', 'bs_fu', 'bs_fu_bb', 'mu_sc', 'four', 'four_no', 'four_v', 'four_v_pif', 'five_v', 'six', 'six_no', 'eight'
    background_computation_strategy: 'threshold'  # threshold, diff_from_max
    softmax_weight: 15
    mask_filtering_threshold: 0.5
  save_dir: '/home/vso/log/bpbreid_market'
  masks_dir: 'pifpaf_maskrcnn_filtering' # 'pifpaf' 'pifpaf_maskrcnn_filtering' 'isp_6_parts'
  workers: 0

sampler:
  train_sampler: RandomIdentitySampler # sampler for source train loader
  train_sampler_t: RandomIdentitySampler # sampler for target train loader
  num_instances: 4 # number of instances per identity for RandomIdentitySampler

model:
  name: 'bpbreid'
  pretrained: True
  save_model_flag: True
  bpbreid:
    pooling: 'gwap'  # ['gap', 'gmp', 'gwap', 'gwap2']
    normalization: 'identity' # 'batch_norm_2d' 'identity'
    mask_filtering_training: False
    mask_filtering_testing: True
    training_binary_visibility_score: True
    testing_binary_visibility_score: True
    last_stride: 1
    learnable_attention_enabled: True
    dim_reduce: 'none' # 'none', 'before_pooling', 'after_pooling', 'after_pooling_with_dropout'
    dim_reduce_output: 512
    backbone: 'fastreid_resnet_ibn_nl' # 'hrnet32' 'resnet50' 'fastreid_resnet' 'fastreid_resnet_ibn' 'fastreid_resnet_nl' 'fastreid_resnet_ibn_nl'
    test_embeddings: ['bn_foreg', 'parts'] #  ['globl', 'foreg', 'conct', 'parts']
    test_use_target_segmentation: 'none' # 'none' 'hard' 'soft'
    shared_parts_id_classifier: False

train:
  batch_size: 64
  eval_freq: 0
  max_epoch: 120 # 45 120
  stepsize: [40, 70] # [40, 70] [25, 35]
  optim: 'adam' # 'adam', 'amsgrad', 'sgd', 'rmsprop', 'radam'
  lr: 0.00035
  lr_scheduler: 'warmup_multi_step' # 'single_step' 'multi_step' 'cosine' 'warmup_multi_step'
  fixbase_epoch: 0
  open_layers: ['global_avgpool', 'foreground_global_attention_pooling_head', 'background_global_attention_pooling_head',
                'global_attention_pooling_head', 'pixel_classifier', 'global_identity_classifier',
                'background_identity_classifier', 'foreground_identity_classifier', 'parts_identity_classifier']

test:
  evaluate: True # test only
  start_eval: 40
  batch_size: 128
  batch_size_pairwise_dist_matrix: 5000
  normalize_feature: True
  dist_metric: 'cosine' # ['euclidean', 'cosine']
  visrank: False
  visrank_per_body_part: False
  vis_embedding_projection: False
  vis_feature_maps: False
  visrank_topk: 10
  visrank_count: 10
  visrank_q_idx_list: []
  part_based:
    dist_combine_strat: mean
