project:
    name: "Person-Re-Identification"
    experiment_name: ""
    notes: ""
    tags: ["test"]
    logger:
      use_clearml: False
      use_neptune: False
      use_tensorboard: True
      use_wandb: True

data:
  root: '~/datasets/reid'
  type: 'image'
  sources: ['dukemtmcreid']
  targets: ['dukemtmcreid']
  height: 384
  width: 128
  combineall: False
  transforms: ['rc', 're']
  masks:
    preprocess: 'five_v'  # 'none', 'full', 'id', 'ids', 'bs_fu', 'bs_fu_bb', 'mu_sc', 'four', 'four_no', 'four_v', 'four_v_pif', 'five_v', 'six', 'six_no', 'eight'
    background_computation_strategy: 'threshold'  # threshold, diff_from_max
    softmax_weight: 15
    mask_filtering_threshold: 0.5
  save_dir: '/home/vso/log/bpbreid_occluded_duke'
  masks_dir: 'pifpaf_maskrcnn_filtering' # 'pifpaf' 'pifpaf_maskrcnn_filtering' 'isp_6_parts'
  workers: 10

sampler:
  train_sampler: RandomIdentitySampler # sampler for source train loader
  train_sampler_t: RandomIdentitySampler # sampler for target train loader
  num_instances: 4 # number of instances per identity for RandomIdentitySampler

model:
  name: 'bpbreid'
  pretrained: True
#  load_weights: "/home/vso/log/posenet_market/2022_02_25_01_40_39_40S25e6aad9-6cb2-4db3-962d-05c7ae095b62/2022_02_25_01_40_39_40S25e6aad9-6cb2-4db3-962d-05c7ae095b62model/model.pth.tar-120" # 7170
#  load_weights: "/home/vso/log/bpbreid_market/2022_03_13_02_10_37_10Sc446d640-96e6-462e-be5f-3d7ea60921b2/2022_03_13_02_10_37_10Sc446d640-96e6-462e-be5f-3d7ea60921b2model/model.pth.tar-120" # 8205
  load_weights: "/home/vso/log/bpbreid_market/2022_04_29_02_59_33_59S8be4228f-685e-4b62-bb99-53d8f43e105e/2022_04_29_02_59_33_59S8be4228f-685e-4b62-bb99-53d8f43e105emodel/model.pth.tar-120" # 8728
  save_model_flag: False
  bpbreid:
    pooling: 'gwap'  # ['gap', 'gmp', 'gwap', 'gwap2']
    normalization: 'identity' # 'batch_norm_2d' 'identity'
    mask_filtering_training: False
    mask_filtering_testing: True
    training_binary_visibility_score: True
    testing_binary_visibility_score: True
    last_stride: 1
    learnable_attention_enabled: True
    dim_reduce: 'after_pooling' # 'none', 'before_pooling', 'after_pooling', 'after_pooling_with_dropout'
    dim_reduce_output: 256
    backbone: 'hrnet32' # 'hrnet32' 'resnet50' 'fastreid_resnet' 'fastreid_resnet_ibn' 'fastreid_resnet_nl' 'fastreid_resnet_ibn_nl'
    test_embeddings: ['bn_foreg', 'parts'] #  ['globl', 'foreg', 'conct', 'parts']
    test_use_target_segmentation: 'none' # 'none' 'hard' 'soft'
    shared_parts_id_classifier: False

test:
  evaluate: True # test only
  start_eval: 90
  batch_size: 64
  batch_size_pairwise_dist_matrix: 5000
  normalize_feature: True
  dist_metric: 'euclidean' # ['euclidean', 'cosine']
  visrank: False
  visrank_per_body_part: False
  vis_embedding_projection: False
  vis_feature_maps: False
  visrank_topk: 15
  visrank_count: 30
  visrank_q_idx_list: [314]
#  visrank_q_idx_list: [ 363, 942, 1974, 2013, 2081, 2145, 2207, 13, 506, 1695, 1772 ]
  #  363 - 0114_c1_f0072838.jpg
  #  942 - 4804_c6_f0202700.jpg
  #  1974 - 0076_c1_f0065392.jpg
  #  2013 - 4681_c6_f0155553.jpg
  #  2081 - 4760_c7_f0184430.jpg
  #  2145 - 0749_c1_f0188383.jpg
  #  2207 - 4726_c6_f0169726.jpg
  part_based:
    dist_combine_strat: mean
