project:
    name: "Person-Re-Identification"
    experiment_name: ""
    notes: "strongsort"
    tags: []
    logger:
      use_clearml: False
      use_neptune: False
      use_tensorboard: True
      use_wandb: True

data:
  root: '~/datasets/reid'
  type: 'image'
  sources: ['dukemtmcreid']
  targets: []
  height: 256 # 384
  width: 128 # 192
  combineall: False
  transforms: ['rc', 're']
  masks:
    preprocess: 'id'  # 'none', 'full', 'id', 'ids', 'bs_fu', 'bs_fu_bb', 'mu_sc', 'four', 'four_no', 'four_v', 'four_v_pif', 'five', 'five_v', 'six', 'six_no', 'seven_v', 'eight', 'eight_v', 'ten_ms', 'eleven', 'fourteen', 'fourteen'
    background_computation_strategy: 'threshold'  # threshold, diff_from_max
    softmax_weight: 15
    mask_filtering_threshold: 0.5
  save_dir: '/home/vso/log/bpbreid_occluded_duke'
  masks_dir: 'pifpaf_maskrcnn_filtering' # 'pifpaf' 'pifpaf_maskrcnn_filtering' 'isp_6_parts'
  workers: 6

sampler:
  train_sampler: RandomIdentitySampler # sampler for source train loader
  train_sampler_t: RandomIdentitySampler # sampler for target train loader
  num_instances: 4 # number of instances per identity for RandomIdentitySampler

model:
  name: 'bpbreid'
  load_weights: "/home/vso/log/bpbreid_occluded_duke/9002/2022_05_26_18_16_09_16Sa91cdfd1-4ba8-486d-a220-4d647c38fc73model/job-9002_120_model.pth.tar" # 9002
  pretrained: True
  save_model_flag: True
  bpbreid:
    pooling: 'gap'  # ['gap', 'gmp', 'gwap', 'gwap2']
    normalization: 'identity' # 'batch_norm_2d' 'identity'
    mask_filtering_training: False
    mask_filtering_testing: False
    training_binary_visibility_score: True
    testing_binary_visibility_score: True
    last_stride: 1
    learnable_attention_enabled: False
    dim_reduce: 'none' # 'none', 'before_pooling', 'after_pooling', 'after_pooling_with_dropout', 'after_pooling_pcb'
    dim_reduce_output: 512
    backbone: 'resnet50' # 'hrnet32' 'resnet50' 'fastreid_resnet' 'fastreid_resnet_ibn' 'fastreid_resnet_nl' 'fastreid_resnet_ibn_nl'
    test_embeddings: ['bn_globl'] #  ['globl', 'foreg', 'conct', 'parts']
    test_use_target_segmentation: 'none' # 'none' 'hard' 'soft'
    shared_parts_id_classifier: False
    normalized_bned_embeddings: False

loss:
  name: 'part_based'
  triplet:
    margin: 0.3
  part_based:
    name: 'part_based_triplet_loss_mean' # ['inter_parts_triplet_loss', 'intra_parts_triplet_loss', 'part_based_triplet_loss_max', 'part_based_triplet_loss_mean', 'part_based_triplet_loss_min', 'part_based_triplet_loss_max_min', 'part_based_triplet_loss_random_max_min']
    weights:
      globl:
        ce: 1.
        tr: 1.
      foreg:
        ce: 0.
        tr: 0.
      conct:
        ce: 0.
        tr: 0.
      parts:
        ce: 0.
        tr: 0.
      pixls:
        ce: 0.

train:
  batch_size: 64
  eval_freq: 0
  max_epoch: 120 # 45 120
  stepsize: [40, 70] # [40, 70] [25, 35]
  optim: 'adam' # 'adam', 'amsgrad', 'sgd', 'rmsprop', 'radam'
  lr: 0.00035
  lr_scheduler: 'warmup_multi_step' # 'single_step' 'multi_step' 'cosine' 'warmup_multi_step'
  fixbase_epoch: 0
  open_layers: ['global_avgpool', 'foreground_global_attention_pooling_head', 'background_global_attention_pooling_head',
                'global_attention_pooling_head', 'pixel_classifier', 'global_identity_classifier',
                'background_identity_classifier', 'foreground_identity_classifier', 'parts_identity_classifier']

test:
  evaluate: True
  start_eval: 90
  detailed_ranking: False
  batch_size: 128
  batch_size_pairwise_dist_matrix: 5000
  normalize_feature: True
  dist_metric: 'euclidean' # ['euclidean', 'cosine']
  visrank: False
  visrank_per_body_part: False
  vis_embedding_projection: False
  vis_feature_maps: False
  visrank_topk: 10
  visrank_count: 11
  visrank_q_idx_list: [ 363, 942, 1974, 2013, 2081, 2145, 2207, 13, 506, 1695, 1772 ]
  #  363 - 0114_c1_f0072838.jpg
  #  942 - 4804_c6_f0202700.jpg
  #  1974 - 0076_c1_f0065392.jpg
  #  2013 - 4681_c6_f0155553.jpg
  #  2081 - 4760_c7_f0184430.jpg
  #  2145 - 0749_c1_f0188383.jpg
  #  2207 - 4726_c6_f0169726.jpg
  part_based:
    dist_combine_strat: mean

inference:
  enabled: True
  input_folder: "/home/vso/projects/StrongSORT/pregenerated_files/MOT17_val_YOLOX_crops_for_reid_simpleCNN"
#  input_folder: "/home/vso/projects/StrongSORT/pregenerated_files/MOT17_val_YOLOX_crops_for_reid"