project:
    name: "Person-Re-Identification"
    experiment_name: ""
    notes: ""
    tags: []
    logger:
      use_clearml: False
      use_neptune: False
      use_tensorboard: True
      use_wandb: True

data:
  root: '~/datasets/reid'
  type: 'image'
  sources: ['market1501']
  targets: ['market1501']
  height: 384 # 384
  width: 128 # 192
  combineall: False
  transforms: ['rc', 'rf', 're']
  save_dir: '/home/vso/log/resnet50_fc512_market1501_train'
  workers: 10

model:
  name: 'resnet50_fc512'
  pretrained: True
  save_model_flag: False

loss:
  name: 'triplet'
  triplet:
    margin: 0.3

train:
  batch_size: 64
  eval_freq: 0
  max_epoch: 120 # 45 120
  stepsize: [40, 70] # [40, 70] [25, 35]
  optim: 'adam' # 'adam', 'amsgrad', 'sgd', 'rmsprop', 'radam'
  lr: 0.00035
  lr_scheduler: 'warmup_multi_step' # 'single_step' 'multi_step' 'cosine' 'warmup_multi_step'  fixbase_epoch: 0

test:
  start_eval: 90
  batch_size: 128
  normalize_feature: True
  dist_metric: 'euclidean' # ['euclidean', 'cosine']
  visrank: False
  visrank_per_body_part: False
  vis_embedding_projection: False
  vis_feature_maps: False
  visrank_topk: 10
  visrank_count: 11